---
- name: deploy pki 2
  hosts: pki
  become: true
  gather_facts: yes
  tasks: 
   - name: install
     apt:
       name: ['default-jdk-headless', 'ant', 'ant-optional', 'unzip','mariadb-server'] 
       state: present

   - name: copy mysql utf8 config
     copy:
       src: mysql/utf-8.conf
       dest: /etc/mysql/conf.d/utf-8.conf
       
   - name: restart mysql service
     service:
       name: mysql
       state: restarted