---
- name: deploy pki 2
  hosts: pki
  become: true
  gather_facts: yes
  tasks: 
   - name: "{{ item }} install"
     apt:
       name: "{{ item }}" 
       state: present
     with_items: 
       - default-jdk-headless
       - ant
       - ant-optional
       - unzip
