---
- name: deploy pki 2
  hosts: pki
  become: true
  gather_facts: yes
  tasks: 
   - name: jdk install
     apt:
       name: default-jdk-headless
       state: present
       
   - name: ant install
     apt:
       name: ant 
       state: present

   - name: ant-optional install
     apt:
       name: ant-optional
       state: present
       
   - name: unzip install
     apt:
       name: unzip
       state: present
