---
- name: deploy pki 2
  hosts: pki
  become: true
  gather_facts: yes
  tasks: 
   - name: install
     apt:
       name: ['default-jdk-headless', 'ant', 'ant-optional', 'unzip','mariadb-server'] 
       state: present

